# === Configuration ===
NAME = push_swap
CC = cc
CFLAGS = -g -Wall -Wextra -Werror
DFLAGS = -MMD -MP -I include

SRCDIR = src
OBJDIR = obj
VEC_DIR = c_vec
VEC_A = $(VEC_DIR)/c_vec.a
LIBFT_DIR = libft
LIBFT_A = $(LIBFT_DIR)/libft.a

# === Source Files ===
SRCS = $(addprefix $(SRCDIR)/,\
	main.c \
	input_validation.c \
	handle_vec.c  \
)

OBJS = $(SRCS:$(SRCDIR)/%.c=$(OBJDIR)/%.o)
# Dependency files generated by -MMD -MP
DEPS = $(OBJS:.o=.d)

# === Default Target ===
all: $(NAME)

# === Build Vec Archive ===
$(VEC_A):
	make -s -C $(VEC_DIR)

$(LIBFT_A):
	make -s -C $(LIBFT_DIR)
# === Build Executable ===
$(NAME): $(OBJS) $(VEC_A) $(LIBFT_A)
		$(CC) $(CFLAGS) $(OBJS) $(VEC_A) $(LIBFT_A) -o $(NAME)

# === Compile Rule for .c to .o ===
#silently make the directory that contains that output file
$(OBJDIR)/%.o: $(SRCDIR)/%.c
			mkdir -p $(@D)
			$(CC) $(CFLAGS) $(DFLAGS) -c $< -o $@

# === Clean rule ===
clean:
		rm -rf $(OBJDIR)
		make clean -s -C $(VEC_DIR)
		make clean -s -C $(LIBFT_DIR)

fclean: clean
		rm -rf $(NAME)
		make fclean -s -C $(VEC_DIR)
		make fclean -s -C $(LIBFT_DIR)

re: fclean all


.PHONY: all clean fclean re
.SECONDARY: $(OBJS)
#includes the .d files, - don’t throw error if doesn’t exist(first build)
-include $(DEPS)