# === Configuration ===
NAME = push_swap
CC = cc
CFLAGS = -Wall -Wextra -Werror
DFLAGS = -MMD -MP -I include

SRCDIR = src
OBJDIR = obj

# === Source Files ===
SRCS = $(addprefix $(SRCDIR)/,\
	main.c \
)
OBJS = $(SRCS:$(SRCDIR)/%.c=$(OBJDIR)/%.o)
# Dependency files generated by -MMD -MP
DEPS = $(OBJS:.o=.d)

# === Default Target ===
all: $(NAME)

# === Build Executable ===
$(NAME): $(OBJS)
		$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

# === Compile Rule for .c to .o ===
#silently make the directory that contains that output file
$(OBJDIR)/%.o: $(SRCDIR)/%.c
			mkdir -p $(@D)
			$(CC) $(CFLAGS) $(DFLAGS) -c $< -o $@

# === Clean rule ===
clean:
		rm -rf $(OBJDIR)

fclean: clean
		rm -rf $(NAME)

re: fclean all


.PHONY: all clean fclean re
.SECONDARY: $(OBJS)
-include $(DEPS)